In [1]:
!ls
from google.colab import drive
drive.mount('/content/drive')

sample_data
Mounted at /content/drive


In [2]:
%cd "./drive/MyDrive/CS786_Project/"

/content/drive/MyDrive/CS786_Project


In [3]:
#!wget https://openscholar.huji.ac.il/sites/default/files/agri_economics/files/rawdataexperiment1sorted.zip

In [4]:
#!unzip rawdataexperiment1sorted.zip

In [5]:
import pandas as pd
import numpy as np

In [6]:
!ls

 combined.csv
'Copy of CS786_Project_Psych_feat.ipynb'
 CS786_Project.ipynb
 CS786_Project_Psych_feat.ipynb
 dxcomp_data_2.csv
 dxcomp_data.csv
'DXcomp Experiment 1 Distribution Data Appended.csv'
'DXcomp Experiment2 (Estimation Set) Distribution Data.csv'
 DXcomp_Experiment3_DistributionData.csv
 exp1.csv
 exp2.csv
 exp3.csv
 exp3.gsheet
 exp3_new.csv
 RawDataExperiment1sorted.csv
 rawdataexperiment1sorted.zip
 rawdataexperiment1sorted.zip.1
 rawdataexperiment1sorted.zip.2
 rawdataexperiment1sorted.zip.3
 rawdataexperiment1sorted.zip.4
 rawdataexperiment1sorted.zip.5
 rawdataexperiment1sorted.zip.6
 rawdataexperiment1sorted.zip.7
 rawdataexperiment1sorted.zip.8
 rawdataexperiment1sorted.zip.9
 test.csv
 test_new.csv
 train.csv


In [7]:
df = pd.read_csv("combined.csv")

In [8]:
df.head()

Problem  Ha   pHa  La  Hb  pHb  Lb Manipulation  Amb LotShape  ...  ssdB  \
0        1   3  1.00   3   4  0.8   0     abstract    0        -  ...   0.4   
1        2   3  0.25   0   4  0.2   0     abstract    0        -  ...   0.4   
2        3  -1  1.00  -1   0  0.5  -2     abstract    0        -  ...   0.5   
3        4   1  1.00   1   2  0.5   0     abstract    0        -  ...   0.5   
4        5  -3  1.00  -3   0  0.2  -4     abstract    0        -  ...   0.4   

        dSD  SignMax  RatioMin      pBetter0  pBetterFB      pBetterU  \
0  1.600000        1      0.00 -9.090909e-02  -1.000000  3.939394e-01   
1  0.300962        1      1.00 -1.313131e-01  -0.578947 -6.969697e-01   
2  1.000000        0      0.50 -3.122502e-17   0.052632 -3.122502e-17   
3  1.000000        1      0.00 -3.122502e-17   0.052632 -3.122502e-17   
4  1.600000        0      0.75  9.090909e-02   1.000000 -3.939394e-01   

   pBetterS  pBetterSFB  Dom  
0  0.393939    7.000000    1  
1  0.878788    1.421053    1  
2 -0.696970  -13.000000    1  
3  0.696970   13.000000    1  
4 -0.393939   -7.000000    1  

[5 rows x 76 columns]

df.head()

In [9]:
df.shape

(150, 76)

In [10]:
df.columns

Index(['Problem', 'Ha', 'pHa', 'La', 'Hb', 'pHb', 'Lb', 'Manipulation', 'Amb',
       'LotShape', 'LotNum', 'Corr', 'av1', 'ap1', 'av2', 'ap2', 'bv1', 'bp1',
       'bv2', 'bp2', 'bv3', 'bp3', 'bv4', 'bp4', 'bv5', 'bp5', 'bv6', 'bp6',
       'bv7', 'bp7', 'bv8', 'bp8', 'bv9', 'bp9', 'bv10', 'bp10', 'B1', 'B2',
       'B3', 'B4', 'B5', 'evA', 'evB', 'minA', 'minB', 'dMins', 'maxA', 'maxB',
       'dMaxs', 'UEVa', 'UEVb', 'dEV0', 'dEV', 'dEVfb', 'dUniEV', 'EVsa',
       'EVsb', 'dSignEV', 'dMins.1', 'sdA', 'sdB', 'countA', 'countB', 'usdA',
       'usdB', 'ssdA', 'ssdB', 'dSD', 'SignMax', 'RatioMin', 'pBetter0',
       'pBetterFB', 'pBetterU', 'pBetterS', 'pBetterSFB', 'Dom'],
      dtype='object')

In [11]:
df["pred_rate"] = 0.0
df["class"] = 0

In [12]:
df_columns = list(df.columns)

In [13]:
B1_idx = df_columns.index("B1")

In [14]:
new_df = df.reindex(df.index.repeat(5))

In [15]:
new_df = new_df.reset_index(drop=True)

In [16]:
new_df

Problem  Ha  pHa  La  Hb   pHb  Lb Manipulation  Amb LotShape  ...  \
0          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
1          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
2          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
3          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
4          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
..       ...  ..  ...  ..  ..   ...  ..          ...  ...      ...  ...   
745      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
746      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
747      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
748      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
749      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   

     SignMax  RatioMin  pBetter0  pBetterFB  pBetterU      pBetterS  \
0          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
1          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
2          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
3          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
4          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
..       ...       ...       ...        ...       ...           ...   
745        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
746        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
747        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
748        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
749        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   

     pBetterSFB  Dom  pred_rate  class  
0      7.000000    1        0.0      0  
1      7.000000    1        0.0      0  
2      7.000000    1        0.0      0  
3      7.000000    1        0.0      0  
4      7.000000    1        0.0      0  
..          ...  ...        ...    ...  
745    0.157895    0        0.0      0  
746    0.157895    0        0.0      0  
747    0.157895    0        0.0      0  
748    0.157895    0        0.0      0  
749    0.157895    0        0.0      0  

[750 rows x 78 columns]

In [17]:
new_df.iloc[0,B1_idx]

0.4224

In [18]:
len(df_columns)

78

In [19]:
for i in range(len(new_df)):
  new_df.iloc[i,len(df_columns) - 2] = new_df.iloc[i,B1_idx + i%5]
  new_df.iloc[i,len(df_columns) - 1] = i%5

In [20]:
new_df

Problem  Ha  pHa  La  Hb   pHb  Lb Manipulation  Amb LotShape  ...  \
0          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
1          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
2          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
3          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
4          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
..       ...  ..  ...  ..  ..   ...  ..          ...  ...      ...  ...   
745      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
746      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
747      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
748      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
749      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   

     SignMax  RatioMin  pBetter0  pBetterFB  pBetterU      pBetterS  \
0          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
1          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
2          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
3          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
4          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
..       ...       ...       ...        ...       ...           ...   
745        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
746        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
747        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
748        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
749        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   

     pBetterSFB  Dom  pred_rate  class  
0      7.000000    1     0.4224      0  
1      7.000000    1     0.5712      1  
2      7.000000    1     0.5680      2  
3      7.000000    1     0.5952      3  
4      7.000000    1     0.6496      4  
..          ...  ...        ...    ...  
745    0.157895    0     0.3500      0  
746    0.157895    0     0.2500      1  
747    0.157895    0     0.2200      2  
748    0.157895    0     0.1900      3  
749    0.157895    0     0.1700      4  

[750 rows x 78 columns]

In [21]:
new_df = new_df.drop(columns=['B1', 'B2','B3','B4','B5'])

In [22]:
new_df

Problem  Ha  pHa  La  Hb   pHb  Lb Manipulation  Amb LotShape  ...  \
0          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
1          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
2          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
3          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
4          1   3  1.0   3   4  0.80   0     abstract    0        -  ...   
..       ...  ..  ...  ..  ..   ...  ..          ...  ...      ...  ...   
745      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
746      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
747      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
748      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   
749      150  16  1.0  16  24  0.05  12            1    0   L-skew  ...   

     SignMax  RatioMin  pBetter0  pBetterFB  pBetterU      pBetterS  \
0          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
1          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
2          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
3          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
4          1      0.00 -0.090909       -1.0  0.393939  3.939394e-01   
..       ...       ...       ...        ...       ...           ...   
745        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
746        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
747        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
748        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   
749        1      0.75  0.797980       15.0 -0.595960  3.122502e-17   

     pBetterSFB  Dom  pred_rate  class  
0      7.000000    1     0.4224      0  
1      7.000000    1     0.5712      1  
2      7.000000    1     0.5680      2  
3      7.000000    1     0.5952      3  
4      7.000000    1     0.6496      4  
..          ...  ...        ...    ...  
745    0.157895    0     0.3500      0  
746    0.157895    0     0.2500      1  
747    0.157895    0     0.2200      2  
748    0.157895    0     0.1900      3  
749    0.157895    0     0.1700      4  

[750 rows x 73 columns]

In [23]:
# Get one hot encoding of columns B
one_hot = pd.get_dummies(new_df['Manipulation'])
# Drop column B as it is now encoded
new_df = new_df.drop('Manipulation',axis = 1)
# Join the encoded df
new_df = new_df.join(one_hot)


In [24]:
new_df.columns

Index(['Problem', 'Ha', 'pHa', 'La', 'Hb', 'pHb', 'Lb', 'Amb', 'LotShape',
       'LotNum', 'Corr', 'av1', 'ap1', 'av2', 'ap2', 'bv1', 'bp1', 'bv2',
       'bp2', 'bv3', 'bp3', 'bv4', 'bp4', 'bv5', 'bp5', 'bv6', 'bp6', 'bv7',
       'bp7', 'bv8', 'bp8', 'bv9', 'bp9', 'bv10', 'bp10', 'evA', 'evB', 'minA',
       'minB', 'dMins', 'maxA', 'maxB', 'dMaxs', 'UEVa', 'UEVb', 'dEV0', 'dEV',
       'dEVfb', 'dUniEV', 'EVsa', 'EVsb', 'dSignEV', 'dMins.1', 'sdA', 'sdB',
       'countA', 'countB', 'usdA', 'usdB', 'ssdA', 'ssdB', 'dSD', 'SignMax',
       'RatioMin', 'pBetter0', 'pBetterFB', 'pBetterU', 'pBetterS',
       'pBetterSFB', 'Dom', 'pred_rate', 'class', '0', '1', '2', 'AcRj',
       'StPb', 'abstract'],
      dtype='object')

In [25]:
# Get one hot encoding of columns B
one_hot = pd.get_dummies(new_df['LotShape'])
# Drop column B as it is now encoded
new_df = new_df.drop('LotShape',axis = 1)
# Join the encoded df
new_df = new_df.join(one_hot)
new_df

Problem  Ha  pHa  La  Hb   pHb  Lb  Amb  LotNum  Corr  ...  0  1  2  \
0          1   3  1.0   3   4  0.80   0    0       1     0  ...  0  0  0   
1          1   3  1.0   3   4  0.80   0    0       1     0  ...  0  0  0   
2          1   3  1.0   3   4  0.80   0    0       1     0  ...  0  0  0   
3          1   3  1.0   3   4  0.80   0    0       1     0  ...  0  0  0   
4          1   3  1.0   3   4  0.80   0    0       1     0  ...  0  0  0   
..       ...  ..  ...  ..  ..   ...  ..  ...     ...   ...  ... .. .. ..   
745      150  16  1.0  16  24  0.05  12    0       3     0  ...  0  1  0   
746      150  16  1.0  16  24  0.05  12    0       3     0  ...  0  1  0   
747      150  16  1.0  16  24  0.05  12    0       3     0  ...  0  1  0   
748      150  16  1.0  16  24  0.05  12    0       3     0  ...  0  1  0   
749      150  16  1.0  16  24  0.05  12    0       3     0  ...  0  1  0   

     AcRj  StPb  abstract  -  L-skew  R-skew  Symm  
0       0     0         1  1       0       0     0  
1       0     0         1  1       0       0     0  
2       0     0         1  1       0       0     0  
3       0     0         1  1       0       0     0  
4       0     0         1  1       0       0     0  
..    ...   ...       ... ..     ...     ...   ...  
745     0     0         0  0       1       0     0  
746     0     0         0  0       1       0     0  
747     0     0         0  0       1       0     0  
748     0     0         0  0       1       0     0  
749     0     0         0  0       1       0     0  

[750 rows x 81 columns]

In [26]:
new_df = new_df.fillna(0)

In [27]:
new_df.columns

Index(['Problem', 'Ha', 'pHa', 'La', 'Hb', 'pHb', 'Lb', 'Amb', 'LotNum',
       'Corr', 'av1', 'ap1', 'av2', 'ap2', 'bv1', 'bp1', 'bv2', 'bp2', 'bv3',
       'bp3', 'bv4', 'bp4', 'bv5', 'bp5', 'bv6', 'bp6', 'bv7', 'bp7', 'bv8',
       'bp8', 'bv9', 'bp9', 'bv10', 'bp10', 'evA', 'evB', 'minA', 'minB',
       'dMins', 'maxA', 'maxB', 'dMaxs', 'UEVa', 'UEVb', 'dEV0', 'dEV',
       'dEVfb', 'dUniEV', 'EVsa', 'EVsb', 'dSignEV', 'dMins.1', 'sdA', 'sdB',
       'countA', 'countB', 'usdA', 'usdB', 'ssdA', 'ssdB', 'dSD', 'SignMax',
       'RatioMin', 'pBetter0', 'pBetterFB', 'pBetterU', 'pBetterS',
       'pBetterSFB', 'Dom', 'pred_rate', 'class', '0', '1', '2', 'AcRj',
       'StPb', 'abstract', '-', 'L-skew', 'R-skew', 'Symm'],
      dtype='object')

In [28]:
from sklearn.ensemble import RandomForestRegressor

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X = np.array(new_df.drop(columns=["pred_rate"]))

In [31]:
X[0]

array([ 1.        ,  3.        ,  1.        ,  3.        ,  4.        ,
        0.8       ,  0.        ,  0.        ,  1.        ,  0.        ,
        3.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.2       ,  4.        ,  0.8       ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  3.        ,
        3.2       ,  3.        ,  0.        , -3.        ,  3.        ,
        4.        ,  1.        ,  3.        ,  2.        ,  0.2       ,
        0.2       ,  0.2       , -1.        ,  1.        ,  0.8       ,
       -0.2       , -3.        ,  0.        ,  1.6       ,  1.        ,
        2.        ,  0.        ,  2.        ,  0.        ,  0.4       ,
        1.6       ,  1.        ,  0.        , -0.09090909, -1.        ,
        0.39393939,  0.39393939,  7.        ,  1.        ,  0.  

In [32]:
X.shape

(750, 80)

In [33]:
y = np.array(new_df["pred_rate"])

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [35]:
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 0)

In [36]:
X_train[0]

array([ 9.50000000e+01, -3.00000000e+00,  5.00000000e-02, -9.00000000e+00,
        4.20000000e+01,  4.00000000e-01, -2.40000000e+01,  0.00000000e+00,
        6.00000000e+00,  1.00000000e+00, -9.00000000e+00,  9.50000000e-01,
       -3.00000000e+00,  5.00000000e-02, -2.40000000e+01,  6.00000000e-01,
       -1.50000000e+01,  1.25000000e-02,  1.70000000e+01,  1.25000000e-02,
        3.30000000e+01,  2.50000000e-02,  4.10000000e+01,  5.00000000e-02,
        4.50000000e+01,  1.00000000e-01,  4.70000000e+01,  2.00000000e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -8.70000000e+00,  2.40000000e+00,
       -9.00000000e+00, -2.40000000e+01, -1.50000000e+01, -3.00000000e+00,
        4.70000000e+01,  5.00000000e+01, -6.00000000e+00,  2.05714286e+01,
        1.11000000e+01,  1.11000000e+01,  1.11000000e+01,  2.65714286e+01,
       -1.00000000e+00, -2.25000000e-01,  7.75000000e-01, -1.50000000e+01,
        1.30766968e+00,  

In [37]:
X_train.shape

(450, 80)

In [38]:
regressor.fit(X_train, y_train) 

RandomForestRegressor(n_estimators=1000, random_state=0)

In [39]:
y_pred = regressor.predict(X_test)

In [40]:
y_pred

array([0.4988573, 0.9820309, 0.5829439, 0.6995902, 0.3249604, 0.8166611,
       0.3129183, 0.6785887, 0.1431028, 0.7992583, 0.3689008, 0.3384429,
       0.7475987, 0.1927845, 0.0515997, 0.3173656, 0.3450259, 0.5800974,
       0.4329483, 0.2011503, 0.3476333, 0.5026123, 0.4362308, 0.6774705,
       0.4341544, 0.3900835, 0.578449 , 0.4232201, 0.4672082, 0.524644 ,
       0.2518891, 0.0264879, 0.9941283, 0.3625282, 0.0330655, 0.698659 ,
       0.1028756, 0.9519649, 0.2750435, 0.950387 , 0.7009367, 0.0618805,
       0.6035619, 0.4928244, 0.0371975, 0.1954526, 0.3375903, 0.4832962,
       0.0413596, 0.9054168, 0.6093727, 0.7908123, 0.0342041, 0.4057189,
       0.0330278, 0.784605 , 0.3933015, 0.7049182, 0.7323002, 0.2057554,
       0.7089839, 0.7203749, 0.4175724, 0.3982532, 0.3367989, 0.2889731,
       0.4810704, 0.4326583, 0.383962 , 0.5577386, 0.3894253, 0.4854121,
       0.4026338, 0.402273 , 0.8563299, 0.4314082, 0.4400647, 0.7651292,
       0.026051 , 0.4066518, 0.4677037, 0.398414 , 

In [41]:
y_test

array([0.51  , 0.995 , 0.5776, 0.7926, 0.3012, 0.73  , 0.27  , 0.6815,
       0.15  , 0.81  , 0.392 , 0.3175, 0.7086, 0.25  , 0.0444, 0.2963,
       0.2896, 0.5975, 0.39  , 0.19  , 0.35  , 0.53  , 0.4875, 0.675 ,
       0.4512, 0.51  , 0.5704, 0.4375, 0.4938, 0.4963, 0.2875, 0.03  ,
       0.99  , 0.37  , 0.0025, 0.832 , 0.1284, 0.98  , 0.3296, 0.9825,
       0.8128, 0.07  , 0.6224, 0.4064, 0.02  , 0.17  , 0.39  , 0.5   ,
       0.015 , 0.88  , 0.5792, 0.83  , 0.0025, 0.45  , 0.02  , 0.6592,
       0.47  , 0.7904, 0.65  , 0.2064, 0.7037, 0.6765, 0.5   , 0.43  ,
       0.2173, 0.2716, 0.5111, 0.4912, 0.315 , 0.54  , 0.23  , 0.37  ,
       0.3556, 0.36  , 0.86  , 0.46  , 0.51  , 0.8784, 0.    , 0.4375,
       0.4198, 0.3712, 0.53  , 0.42  , 0.416 , 0.8225, 0.54  , 0.71  ,
       0.38  , 0.6208, 0.41  , 0.3824, 0.26  , 0.35  , 0.416 , 0.4775,
       0.71  , 0.5111, 0.4784, 0.0494, 0.328 , 0.6   , 0.568 , 0.84  ,
       0.6691, 0.4784, 0.33  , 0.98  , 0.5525, 0.2198, 0.81  , 0.78  ,
      

In [42]:
MSE = np.square(np.subtract(y_test,y_pred)).mean()
MSE*100

0.3299372402767621